var TEXTS_EL = {
  title: "Stand by Me Game",
  subtitle: "Καλωσορίσατε στον κόσμο του Stand By Me: ένας ιδιαίτερος πλανήτης με ανεπαίσθητα όρια, όπου κάθε κάτοικος, στην ηλικία των 16 ετών, αφήνει το σπίτι και την οικογένεια του και έρχεται σε επαφή καινούργιες περιπέτειες και προκλήσεις τις οποίες αντιμετωπίζει με τις μοναδικές υπερδυνάμεις του/της.",
  download_button: "Κατεβάστε ",
  description: "Αυτό το σενάριο σχετίζεται με την καθημερινότητα αγοριών και κοριτσιών που εγκαταλείπουν τις κρατικές υπηρεσίες προστασίας και καλούνται να αντιμετωπίσουν την πρόκληση της αυτονομίας νωρίτερα από τους συνομηλίκους τους. Το παιχνίδι είναι ένα εργαλείο ευαισθητοποίησης και κριτικής σκέψης σχετικά με την αυτονομία και την ανάπτυξη, το οποίο έχει δημιουργηθεί στα πλαίσια του Ευρωπαϊκού έργου Stand By Me. Είναι ιδανικό ανεξαρτήτως φύλου και ηλικίας. Διατίθεται δωρεάν στο διαδίκτυο.",
  slogan: "ένα εργαλείο ευαισθητοποίησης και κριτικής σκέψης σχετικά με την αυτονομία και την ανάπτυξη",
  creative_commons: "Το Stand by Me είναι ένα επιτραπέζιο παιχνίδι ανοιχτού κώδικα με άδεια Creative Commons (Attribution-ShareAlike 3.0 Unported — CC BY-SA 3.0).",
  editable: "Είναι επεξεργάσιμο και μπορεί να τροποποιηθεί από τους χρήστες προκειμένου να προσαρμοστεί το περιεχόμενο σε συγκεκριμένες ανάγκες (γλώσσα, ισορροπία μεταξύ των φύλων, τύπος ιστορίας). ",
  enjoy: "Απολαύστε το! ",
  realized_by: "Το έργο υλοποιήθηκε από τους οργανισμούς:",
  realizad_by_text: "Metropolitan City of Milan (Ιταλία), Codici | Research and intervention (Ιταλία), Spazio Aperto Servizi (Ιταλία), Ahead (Ρουμανία), Eurosuccess (Κύπρος) και Fryshuset (Σουηδία)",
  board_created_by: "Το επιτραπέζιο παιχνίδι δημιουργήθηκε από:",
  project_sbm: "Το έργο Stand by Me",
  code_sbm: "REC–RCH–PROF–AG–2017–785708",
  collaboration: "Σε συνεργασία με:",
  collaboration_text: "wemake.cc featuring smarketing°",
  illustrations: "Εικονογραφήσεις",
  illustrations_text: "strambetty.com",
  more_info: "Για περισσότερες πληροφορίες:",
  more_info_text: "standbyme.rec@gmail.com",
  disclaimer: "Δήλωση αποποίησης ευθύνης: Αυτό το παιχνίδι βασίζεται στη μυθοπλασία και οποιαδήποτε αναφορά σε άτομα, μέρη και γεγονότα είναι καθαρά τυχαία. Όλα τα περιεχόμενα και χαρακτήρες του παιχνιδιού SBM έχουν δημιουργηθεί σε σχέση με τις πολιτισμικές και γλωσσικές διαφορές, καθώς και την ισορροπία μεταξύ των φύλων.",
  warning: "This github pages reflect the views only of the author and the Commission cannot be held responsible for any use which may be made of the information contained therein. REC–RCH–PROF–AG–2017–785708",
  funded_by: "This project was funded by the European Union’s Rights, Equality and Citizenship Programme (2014-2020)"
}
