var TEXTS_EN = {
  title: "Stand by Me Game",
  subtitle: "Welcome to the Stand by Me world: an oddly shaped planet with imperceptible borders where every resident, at the age of 16 years old, leaves his/her home and families to face extraordinary adventures and challenges with their superpowers.",
  slogan: "An awareness and critical thinking tool about autonomy and growing up.",
  download_button: "Download",
  description: "This scenario applies daily to boys and girls leaving the alternative care system and that are asked to face and cope with the challenges of autonomy earlier than their peers. This free and downloadable game is an awareness and critical thinking tool about autonomy and growing up, built through a participative process thanks to the Stand by Me European project. The game applies to boys and girls but also to the adults going along with them.",
  creative_commons: "Stand by Me is an open source board game under a Creative Commons License (Attribution-ShareAlike 3.0 Unported — CC BY-SA 3.0).",
  editable: "It’s editable and might be modified by users in order to adapt contents to specific needs (language, gender-balance, type of story).",
  enjoy: "Enjoy!",
  realized_by: "Project realized by:",
  realizad_by_text: "Metropolitan City of Milan (IT), Codici | Research and intervention (IT), Spazio Aperto Servizi (IT), Ahead (RO), Eurosuccess (CY) and Fryshuset (SE).",
  board_created_by: "Board game created by:",
  project_sbm: "Project Stand by Me",
  code_sbm: "REC–RCH–PROF–AG–2017–785708",
  collaboration: "In collaboration with:",
  collaboration_text: "wemake.cc featuring smarketing°",
  illustrations: "Illustrations:",
  illustrations_text: "strambetty.com",
  more_info: "For more information",
  more_info_text: "standbyme.rec@gmail.com",
  disclaimer: "Disclaimer: This game is based on fiction and any reference to people, places, and events are purely coincidental. All contents and characters of the SBM Game have been created in respect of cultural differences, gender balance and language differences.",
  warning: "This github pages reflect the views only of the author and the Commission cannot be held responsible for any use which may be made of the information contained therein. REC–RCH–PROF–AG–2017–785708",
  funded_by: "This project was funded by the European Union’s Rights, Equality and Citizenship Programme (2014-2020)",
  kit_download: "Game kit download:",
  print_pack: "Game board print pack!",
  instructions_booklet: "Instructions booklet",
  card_stories_booklet: "Cards & Stories booklet",
  packaging_kit: "Packaging and dissemination kit:",
  bussiness_card: "Business card",
  box_folder: "Box folder",
  edit_download: "If you wish to edit the game download also:",
  edit_card_stories_booklet: "Cards & Stories booklet",
  edit_instructions_booklet: "Instructions booklet",
  font: "Font",
  downloads: {
    print_pack: "downloads/200512-SBM-gameboard-printpack-A4-FrontRear-en.pd",
    instructions_booklet: "downloads/EN_StandByMeBoardGame/EN_StandByMeGame__Gamekitdownload/EN_Instructions_booklet_StandByMeBoardGame.pdf",
    card_stories_booklet: "downloads/EN_StandByMeBoardGame/EN_StandByMeGame__Gamekitdownload/EN_Cards&Stories_booklet_StandByMeBoardGame.pdf",
    edit_card_stories_booklet: "downloads/EN_StandByMeBoardGame/EN_StandByMeGame_editablefiles/EN_Cards_Stories_booklet_editablefiles_StandByMeGame.docx",
    edit_instructions_booklet: "downloads/EN_StandByMeBoardGame/EN_StandByMeGame_editablefiles/EN_Instructions_booklet_editablefiles_StandByMeGame.docx",
    bussiness_card: "downloads/Packaging_dissemination_kit_StandByMeGame/StandByMeGame_businesscard.pdf",
    box_folder: "downloads/Packaging_dissemination_kit_StandByMeGame/StandByMeGame_box folder.pdf",
    font: "downloads/Fonts/fonts.zip"
  }
}
