var TEXTS_IT = {
  title: "Stand by Me Game",
  subtitle: "Benvenuti e benvenute nel Mondo di Stand by Me: un pianeta dalle forme strane e dai confini impercettibili dove ogni abitante, compiuti sedici anni, lascia la propria casa e la propria famiglia per affrontare avventure e sfide mirabolanti, con i propri superpoteri.",
  slogan: "Uno  strumento di sensibilizzazione e pensiero critico sui temi della crescita e dell’autonomia",
  download_button: "Scarica",
  description: "Questo è molto simile a quanto accade ogni giorno a ragazzi e ragazze in uscita dai sistemi di accoglienza e affido a cui viene chiesto di affrontare le sfide dell’autonomia molto prima dei propri coetanei. Il gioco, gratuito e scaricabile online, è stato costruito in modo partecipato grazie al progetto europeo Stand by Me, come strumento di sensibilizzazione e pensiero critico sui temi della crescita e dell’autonomia. Si rivolge a ragazzi e ragazze, ma anche agli adulti che li accompagnano.",
  creative_commons: "Stand by Me è un gioco da tavolo open source con licenza Creative Commons (Attribution-ShareAlike 3.0 Unported — CC BY-SA 3.0).",
  editable: "Il gioco è editabile, può quindi essere modificato da chi lo utilizza per adattarsi a contenuti a esigenze specifiche (lingua, genere, tipo di storia).",
  enjoy: "Enjoy!",
  realized_by: "Progetto realizzato da:",
  realizad_by_text: "Città Metropolitana di Milano (IT), Codici | Ricerca e intervento (IT), Spazio Aperto Servizi (IT), Ahead (RO), Eurosuccess (CY) e Fryshuset (SE)",
  board_created_by: "Gioco da tavolo creato da:",
  project_sbm: "Progetto Stand by Me",
  code_sbm: "REC–RCH–PROF–AG–2017–785708",
  collaboration: "In collaborazione con:",
  collaboration_text: "wemake.cc featuring smarketing°",
  illustrations: "Illustrazioni:",
  illustrations_text: "strambetty.com",
  more_info: "Per più informazioni: ",
  more_info_text: "standbyme.rec@gmail.com",
  disclaimer: "Questo gioco è basato sulla finzione e qualsiasi riferimento a persone, luoghi ed eventi è puramente casuale. Tutti i contenuti e i personaggi del gioco Stand by Me sono stati creati nel rispetto delle differenze culturali, dell'equilibrio di genere e delle differenze linguistiche. ",
  warning: "This github pages reflect the views only of the author and the Commission cannot be held responsible for any use which may be made of the information contained therein. REC–RCH–PROF–AG–2017–785708",
  funded_by: "This project was funded by the European Union’s Rights, Equality and Citizenship Programme (2014-2020)",
  kit_download: "Game kit download:",
  print_pack: "Game board da stampare!",
  instructions_booklet: "Istruzioni",
  card_stories_booklet: "Carte e Storie",
  packaging_kit: "Packaging e diffusione:",
  bussiness_card: "Biglietti da visita",
  box_folder: "Scatola",
  edit_download: "Se vuoi modificare il gioco scarica anche",
  edit_card_stories_booklet: "Carte e Storie (editabile)",
  edit_instructions_booklet: "Istruzioni (editabile)",
  font: "Font",
  downloads: {
    print_pack: "downloads/200512-SBM-gameboard-printpack-A4-FrontRear-en.pdf",
    instructions_booklet: "downloads/IT_StandByMeBoardGame/IT_Gamekitdownload_StandByMeGame/IT_Istruzioni_StandByMeGame.pdf",
    card_stories_booklet: "downloads/IT_StandByMeBoardGame/IT_Gamekitdownload_StandByMeGame/IT_Carte_Storie_StandByMeGame.pdf",
    edit_card_stories_booklet: "downloads/IT_StandByMeBoardGame/IT_FileEditabili_StandByMeGame/IT_Carte_Storie_FileEditabili_StandByMegame.docx",
    edit_instructions_booklet: "downloads/IT_StandByMeBoardGame/IT_FileEditabili_StandByMeGame/IT_Istruzioni_FileEditabili_StandByMegame.docx",
    bussiness_card: "downloads/Packaging_dissemination_kit_StandByMeGame/StandByMeGame_businesscard.pdf",
    box_folder: "downloads/Packaging_dissemination_kit_StandByMeGame/StandByMeGame_box folder.pdf",
    font: "downloads/Fonts/fonts.zip"
  }
}
