var TEXTS_RO = {
  title: "Stand by Me Game",
  subtitle: "Bine ați venit în lumea Stand by Me: o planetă ciudată, cu granițe imperceptibile, în care fiecare locuitor, după vârsta de 16 ani își lasă casele și familiile pentru a se confrunta cu provocări şi aventuri extraordinare, folosindu-şi doar superputerile lor.",
  slogan: "este un instrument de conștientizare și gândire critică, despre autonomie și evoluţie",
  download_button: "Descarca",
  description: "Acest scenariu se întâmplă zilnic cu tinerii care părăsesc sistemul de protecţie și cărora li se cere să facă față provocărilor unei vieţi independente mai devreme decât semenii lor. Acest joc gratuit și descărcabil este un instrument de conștientizare și gândire critică, despre autonomie și evoluţie, construit printr-un proces participativ datorită proiectului european Stand by Me. Jocul este recomandat băieților și fetelor, dar și lucrătorilor de tineret.",
  creative_commons: "Stand by Me este un joc de masă gratis, cu licență Creative Commons (Attribution-ShareAlike 3.0 Unported - CC BY-SA 3.0).",
  editable: "Este editabil și poate fi modificat de către utilizatori pentru a adapta conținutul la nevoile specifice (limbă, echilibru de gen, tip de poveste).",
  enjoy: "Succes!",
  realized_by: "Proiect realizat de:",
  realizad_by_text: "Metropolitan City of Milan (IT), Codici | Research and intervention (IT), Spazio Aperto Servizi (IT), Asociaţia MERGI ÎNAINTE (RO), Eurosuccess (CY) și Fryshuset (SE)",
  board_created_by: "Joc de masă creat de: ",
  project_sbm: "Proiect Stand by Me ",
  code_sbm: "REC-RCH-PROF-AG-2017-785708 ",
  collaboration: "În colaborare cu: ",
  collaboration_text: "wemake.cc  şi smarketing° ",
  illustrations: "ilustraţii:",
  illustrations_text: "strambetty.com ",
  more_info: "Pentru mai multe informatii:",
  more_info_text: "standbyme.rec@gmail.com",
  disclaimer: "Disclaimer: Acest joc se bazează pe ficțiune și orice referire la oameni, locuri și evenimente sunt pur coincidente. Toate conținuturile și personajele jocului SBM au fost create ţinând cont de  diferențele culturale, echilibrul de gen și diferențele de limbaj.",
  warning: "This github pages reflect the views only of the author and the Commission cannot be held responsible for any use which may be made of the information contained therein. REC–RCH–PROF–AG–2017–785708",
  funded_by: "This project was funded by the European Union’s Rights, Equality and Citizenship Programme (2014-2020)"
}
