var TEXTS_SV = {
  title: "Stand by Me",
  subtitle: "Välkommen till Stand by Me-världen: en underligt formad planet med omärkbara begränsningar där alla medborgare, vid en ålder av 16 år, lämnar sitt hem och sina familjer för att möta speciella äventyr och utmaningar med sina superkrafter.",
  slogan: "Ett medvetenhets-och kritiskt tänkande verktyg om självständighet och uppväxt",
  download_button: "ladda ner",
  description: "Detta scenario är något som är vardag för de pojkar och flickor som lämnar det alternativa vårdsystemet och som uppmanas att möta och hantera de utmaningarna som kommer med en sådan självständighet tidigare än sina kamrater. Detta gratis och nedladdningsbara spelet är ett medvetenhets-och kritiskt tänkande verktyg om självständighet och uppväxt byggt genom en deltagande process tack vare Stand by Me Europaprojekt. Spelet tillämpas pojkar och flickor men också de vuxna som följer dem.",
  creative_commons: "Stand by Me är ett brädspel med öppen källkod under en Creative Commons-licens (Attribution-ShareAlike 3.0 Unported - CC BY-SA 3.0). ",
  editable: "Spelet kan redigeras och ändras av användare för att anpassa innehållet till specifika behov (språk, könsbalans, berättelsetyp) ",
  enjoy: "Lycka till!",
  realized_by: "Projekt realiserat av:",
  realizad_by_text: "Metropolitan City of Milan (IT), Codici | Research and intervention (IT), Spazio Aperto Servizi (IT), Ahead (RO), Eurosuccess (CY) och Fryshuset (SE)",
  board_created_by: "Brädspel skapat av:",
  project_sbm: "Project Stand by Me",
  code_sbm: "REC–RCH–PROF–AG–2017–785708",
  collaboration: "I samarbete med:",
  collaboration_text: "wemake.cc med smarketing°",
  illustrations: "Illustrationer:",
  illustrations_text: "strambetty.com",
  more_info: "För mer information:",
  more_info_text: "standbyme.rec@gmail.com",
  disclaimer: "Observera: Detta spel är baserat på fiktion och alla hänvisningar till människor, platser och händelser är rent sammanfallande. Allt innehåll och karaktärer i SBM-spelet har skapats med avseende på kulturella skillnader, könsbalans och språkskillnader. ",
  warning: "This github pages reflect the views only of the author and the Commission cannot be held responsible for any use which may be made of the information contained therein. REC–RCH–PROF–AG–2017–785708",
  funded_by: "This project was funded by the European Union’s Rights, Equality and Citizenship Programme (2014-2020)",
  kit_download: "Game kit download:",
  print_pack: "Game board print pack!",
  instructions_booklet: "Instructions booklet",
  card_stories_booklet: "Cards & Stories booklet",
  packaging_kit: "Packaging and dissemination kit:",
  bussiness_card: "Business card",
  box_folder: "Box folder",
  edit_download: "If you wish to edit the game download also:",
  edit_card_stories_booklet: "Cards & Stories booklet",
  edit_instructions_booklet: "Instructions booklet",
  font: "Font",
  downloads: {
    print_pack: "downloads/200512-SBM-gameboard-printpack-A4-FrontRear-en.pdf",
    instructions_booklet: "downloads/StandByMeBoardGame_SE/SE_StandByMeGame__Gamekitdownload/standbymegame_RIKTLINJER SE.pdf",
    card_stories_booklet: "downloads/StandByMeBoardGame_SE/SE_StandByMeGame__Gamekitdownload/standbymegame_KORT _ BERÄTTELSER SE.pdf",
    edit_card_stories_booklet: "downloads/StandByMeBoardGame_SE/SE_StandByMeGame_editablefiles/standbymegame_KORT _ BERÄTTELSER SE.docx",
    edit_instructions_booklet: "downloads/StandByMeBoardGame_SE/SE_StandByMeGame_editablefiles/standbymegame_RIKTLINJER SE.docx",
    bussiness_card: "downloads/Packaging_dissemination_kit_StandByMeGame/StandByMeGame_businesscard.pdf",
    box_folder: "downloads/Packaging_dissemination_kit_StandByMeGame/StandByMeGame_box folder.pdf",
    font: "downloads/Fonts/fonts.zip"
  }
}
